# Replace 'YOUR_ALPHA_VANTAGE_API_KEY' and 'YOUR_OPENAI_API_KEY' with your actual API keys
ALPHA_VANTAGE_API_KEY = '7RFQXDWPMI7B1VTA'
OPENAI_API_KEY = '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'
